"""
pytest 配置和 fixtures
"""
import os
import sys
import pytest
import tempfile
import shutil
from pathlib import Path

# 添加项目根目录到路径
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))


@pytest.fixture(scope="session")
def project_root():
    """获取项目根目录"""
    return Path(__file__).parent.parent


@pytest.fixture
def temp_dir():
    """创建临时目录"""
    temp_path = tempfile.mkdtemp(prefix="ytdl_test_")
    yield temp_path
    # 清理
    if os.path.exists(temp_path):
        shutil.rmtree(temp_path, ignore_errors=True)


@pytest.fixture
def temp_file(temp_dir):
    """创建临时文件"""
    fd, temp_path = tempfile.mkstemp(dir=temp_dir, suffix=".txt")
    os.close(fd)
    yield temp_path
    # 清理
    if os.path.exists(temp_path):
        os.remove(temp_path)


@pytest.fixture
def sample_video_info():
    """示例视频信息"""
    return {
        'id': 'dQw4w9WgXcQ',
        'title': 'Test Video Title',
        'description': 'Test description',
        'duration': 212,
        'uploader': 'Test Uploader',
        'uploader_id': 'TestUploaderID',
        'upload_date': '20230101',
        'view_count': 1000000,
        'like_count': 50000,
        'thumbnail': 'https://example.com/thumb.jpg',
        'is_live': False,
        'formats': [
            {
                'format_id': '137',
                'ext': 'mp4',
                'width': 1920,
                'height': 1080,
                'fps': 30,
                'vcodec': 'avc1',
                'acodec': 'none',
                'filesize': 100000000
            },
            {
                'format_id': '140',
                'ext': 'm4a',
                'vcodec': 'none',
                'acodec': 'mp4a',
                'abr': 128,
                'filesize': 5000000
            }
        ]
    }


@pytest.fixture
def sample_cookie_content():
    """示例 Cookie 内容"""
    return """# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by yt-dlp. Do not edit.

.youtube.com	TRUE	/	TRUE	1735689600	SID	test_session_id_123
.youtube.com	TRUE	/	TRUE	1735689600	SSID	test_ssid_456
.youtube.com	TRUE	/	TRUE	1735689600	HSID	test_hsid_789
"""


@pytest.fixture
def event_bus():
    """获取事件总线实例"""
    from src.core.event_bus import EventBus
    bus = EventBus()
    yield bus
    bus.clear()

